# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190219_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Date_str',
            field=models.DateField(default='2019-2-19', max_length=64),
        ),
    ]
