# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190219_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Date_str',
            field=models.CharField(default='2019-2-19', max_length=64),
        ),
    ]
